/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/api`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/config`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/envoyer`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/history`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/user`; params?: Router.UnknownInputParams; } | { pathname: `/src/Pages/admin`; params?: Router.UnknownInputParams; } | { pathname: `/src/Pages/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/src/api`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Component/config`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Component/envoyer`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Component/history`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Component/user`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Pages/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Pages/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/src/api${`?${string}` | `#${string}` | ''}` | `/src/Component/config${`?${string}` | `#${string}` | ''}` | `/src/Component/envoyer${`?${string}` | `#${string}` | ''}` | `/src/Component/history${`?${string}` | `#${string}` | ''}` | `/src/Component/user${`?${string}` | `#${string}` | ''}` | `/src/Pages/admin${`?${string}` | `#${string}` | ''}` | `/src/Pages/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/api`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/config`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/envoyer`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/history`; params?: Router.UnknownInputParams; } | { pathname: `/src/Component/user`; params?: Router.UnknownInputParams; } | { pathname: `/src/Pages/admin`; params?: Router.UnknownInputParams; } | { pathname: `/src/Pages/login`; params?: Router.UnknownInputParams; };
    }
  }
}
